apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: konnek-consumer
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    spec:
      container:
        image: jonatasbaldin/konnek-knative-consumer
